//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Integratedbak.rc 使用
//
#define IDS_Category_Acquisition        1
#define IDS_Category_Analysis           2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_SCROLLBAR_HOR               101
#define IDC_SCROLLBAR_VER               102
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_IntegratedTYPE              130
#define IDD_DIALOG_SampleParam          136
#define IDD_DIALOG_SampleProg           138
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DIALOG_DataAcquisition      310
#define ID_COMBO_MonitorMode            313
#define IDI_ICON                        316
#define IDB_Category_Large              335
#define IDB_Category_Small              336
#define IDB_TB_ICON                     339
#define IDB_SPLASH                      342
#define IDR_ACCELERATOR1                343
#define IDR_RIBBON1                     344
#define IDD_DIALOG_Analysis_Single      345
#define IDD_DIALOG_Analysis_Multi       347
#define IDD_DIALOG_Analysis_Result      348
#define IDD_DIALOG_Tip                  353
#define IDB_Category_Analysis_Large     355
#define IDB_Category_Analysis_Small     356
#define IDR_MENU_Settings               357
#define IDC_STATIC_GExposure            1000
#define IDC_STATIC_Camera_Interval      1002
#define IDC_STATIC_Camera_SamplingNumber 1003
#define IDC_STATIC_Percent              1003
#define IDC_EDIT_Camera_Exposure        1004
#define IDC_STATIC_Analysis_Result      1004
#define IDC_STATIC_GGain                1005
#define IDC_STATIC_Analysis_SIngle      1005
#define IDC_STATIC_TAG1                 1006
#define IDC_EDIT_Camera_Interval2       1006
#define IDC_STATIC_TAG2                 1007
#define IDC_EDIT_Camera_SamplingNumber2 1007
#define IDC_STATIC_Camera_Interval_Unit 1008
#define IDC_EDIT_IMG1                   1008
#define IDC_STATIC_Camera_Filename      1009
#define IDC_EDIT_IMG2                   1009
#define IDC_EDIT_Camera_Filename        1010
#define IDC_BN_LOAD1                    1010
#define IDC_STATIC_Camera_SamplingDate  1011
#define IDC_BN_LOAD2                    1011
#define IDC_STATIC_TAG3                 1012
#define IDC_EDIT_Camera_Gain            1013
#define IDC_EDIT_MDWAVELENGTH           1013
#define IDC_STATIC_Camera_Gain_Unit     1014
#define IDC_STATIC_TAG4                 1014
#define IDC_STATIC_TAG5                 1015
#define IDC_EDIT_BANDWIDTH              1016
#define IDC_STATIC_TAG6                 1017
#define IDC_STATIC_TAG7                 1018
#define IDC_EDIT_SGLFRECOUNT            1019
#define IDC_STATIC_TAG8                 1020
#define IDC_EDIT_BG_S                   1021
#define IDC_BN_LOAD3                    1022
#define IDC_STATIC_TAG9                 1023
#define IDC_EDIT_COLORMAX               1025
#define IDC_BN_RUN                      1026
#define IDC_STATIC_Analysis_Multi       1027
#define IDC_STATIC_TAG13                1027
#define IDC_STATIC_TAG10                1028
#define IDC_EDIT_FolderNameS            1028
#define IDC_STATIC_TAG11                1029
#define IDC_BN_LOAD4                    1029
#define IDC_STATIC_TAG12                1030
#define IDC_EDIT_COLORMIN               1030
#define IDC_EDIT_STARTIMG               1031
#define IDC_EDIT_ENDIMG                 1032
#define IDC_EDIT_MDWAVELEN              1033
#define IDC_EDIT_BG_M                   1034
#define IDC_EDIT_MINAMP                 1035
#define IDC_EDIT_MAXAMP                 1036
#define IDC_EDIT_FRECOUNT               1037
#define IDC_BN_UNWRAP                   1038
#define IDC_MENU_BN                     1039
#define IDC_STATIC_TAG14                1039
#define IDC_BN_WRAP                     1040
#define IDC_PROGRESS                    1040
#define IDC_EDIT_FolderNameM            1041
#define IDC_BN_LOAD5                    1042
#define IDC_RADIO_Single                1042
#define IDC_RADIO_Multi                 1043
#define IDC_EDIT_Camera_Filename2       1043
#define IDC_EDIT_Camera_SamplingNumber  1044
#define IDC_EDIT_Camera_Interval        1045
#define IDC_STATIC_Acquiring            1046
#define IDC_BN_StartAnalysis            1046
#define IDC_RADIO_AF_Bgshot             1046
#define IDC_PROGRESS_Acquiring          1047
#define IDC_EDIT_BINNING_HOR            1047
#define IDC_EDIT_BINNING_VER            1048
#define IDC_EDIT_Target_width           1048
#define IDC_EDIT_OffsetY                1049
#define IDC_EDIT_Target_Height          1049
#define IDC_EDIT_Camera_SamplingDate    1050
#define IDC_EDIT_OffsetX                1050
#define IDC_STATIC_TAG15                1050
#define IDC_EDIT_Width                  1051
#define IDC_STATIC_TAG16                1051
#define IDC_EDIT_Height                 1052
#define IDC_STATIC_TAG17                1052
#define IDC_EDIT_Target_width2          1053
#define IDC_STATIC_TAG20                1053
#define IDC_EDIT_Target_width3          1054
#define IDC_EDIT_Target_Height2         1054
#define IDC_EDIT_MLTEC                  1055
#define IDC_EDIT_MLTSR                  1056
#define IDC_STATIC_TAG18                1057
#define IDC_EDIT_SGLER                  1057
#define IDC_STATIC_TAG19                1058
#define IDC_EDIT_SGLSR                  1058
#define IDC_EDIT_SGLSC                  1059
#define IDC_EDIT_MLTER                  1059
#define IDC_EDIT_SGLEC                  1060
#define IDC_EDIT_MLTOFFSET              1061
#define IDC_EDIT2                       1062
#define IDC_EDIT_MLTSC                  1062
#define IDC_EDIT_PHASEMIN               1062
#define IDC_EDIT1                       1063
#define IDC_EDIT_SGLOFFSET              1063
#define IDC_EDIT_PHASESTEP              1063
#define IDC_EDIT3                       1064
#define IDC_EDIT_PHASEMAX               1064
#define IDC_STATIC_TEXT                 1065
#define IDC_SHOW_XY                     1066
#define IDC_BUTTON_Monitor              1096
#define IDC_STATIC_Picture              1100
#define IDC_STATIC_Camera_SamplingNumber_Unit 1104
#define IDC_BUTTON_Sampling             1105
#define IDC_SLIDER_Exposure             1115
#define IDC_SLIDER_Gain                 1116
#define IDC_COMBO_Exposure_Unit         1117
#define IDC_BUTTON_CONTINUE             1118
#define IDC_BUTTON_RETURN               1119
#define IDC_PERCENT                     3041
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BN_Monitor                   32772
#define ID_BN_Acquisition               32773
#define ID_BN_ZOOMIN                    32774
#define ID_BN_ZOOMOUT                   32775
#define ID_BN_ZOOMRESET                 32776
#define ID_ABOUT                        32777
#define ID_BN_Bgshot                    32778
#define ID_BN_Single                    32779
#define ID_BN_Multi                     32795
#define ID_SGLCOLOR                     32805
#define ID_SGLGRAY                      32806
#define ID_MULTIUNCOLOR                 32807
#define ID_MULTICOLOR                   32808
#define ID_MULTIUNGRAY                  32809
#define ID_MULTIGRAY                    32810
#define ID_SAVE                         32811
#define ID_BN_Settings                  32812
#define ID_BUTTON2                      32813
#define ID_32814                        32814
#define ID_32815                        32815
#define ID_32816                        32816
#define ID_32817                        32817
#define ID_32818                        32818
#define ID_BN_SaveBMP                   32819
#define ID_BN_Save                      32820
#define ID_BN_SaveJPEG                  32821
#define ID_BN_SaveTIFF                  32822
#define ID_BN_SaveGIF                   32823
#define ID_COMBO_ColorMode              32825

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        359
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
